version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails server -p 3200 -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3200:3200"

  playwright:
    image: mcr.microsoft.com/playwright:v1.47.0-noble
    entrypoint: ["npx", "playwright", "run-server", "--port", "4445"]
    ports:
      - "4445:4445"
